import { z } from 'zod';

export const configValidationSchema = z.object({
  NODE_ENV: z.string(),
  DATABASE_URL: z.string(),
  PORT: z.string(),
  JWT_SECRET: z.string(),
  JWT_EXPIRES_IN: z.string(),
  JWT_REFRESH_SECRET: z.string(),
  JWT_REFRESH_EXPIRES_IN: z.string(),
  CACHE_TTL: z.string(),
  MP_PUBLIC_KEY: z.string(),
  MP_ACCESS_TOKEN: z.string(),
  MP_BASE_URL: z.string(),
  MP_PAYMENT_URL: z.string(),
  PAYWAY_SITE_ID: z.string().optional(),
  PAYWAY_PUBLIC_API_KEY: z.string().optional(),
  PAYWAY_PRIVATE_API_KEY: z.string().optional(),
  PAYWAY_BASE_URL: z.string().optional(),
  COOKIE_SECRET: z.string(),
  BACKEND_BASE_URL: z.string(),
  EMAIL_FROM: z.string(),
  EMAIL_PASS: z.string(),
  FRONTEND_BASE_URL: z.string(),
  GOOGLE_CLIENT_EMAIL: z.string(),
  GOOGLE_CLIENT_PRIVATE_KEY: z.string(),
  GOOGLE_SHEET_ID: z.string(),
  GOOGLE_SHEET_SAME_DAY_ID: z.string(),
  CLOUDINARY_CLOUD_NAME: z.string(),
  CLOUDINARY_API_KEY: z.string(),
  CLOUDINARY_API_SECRET: z.string(),
  OAUTH_CLIENT_ID: z.string(),
  OAUTH_CLIENT_SECRET: z.string(),
  META_ACCESS_TOKEN: z.string(),
  GOOGLE_MAPS_API_KEY: z.string(),
});
