import { registerAs } from '@nestjs/config';

export default registerAs('env', () => ({
  env: process.env.NODE_ENV,
  database_url: process.env.DATABASE_URL,
  port: process.env.PORT,
  jwt_secret: process.env.JWT_SECRET,
  jwt_expires_in: process.env.JWT_EXPIRES_IN,
  jwt_refresh_secret: process.env.JWT_REFRESH_SECRET,
  jwt_refresh_expires_in: process.env.JWT_REFRESH_EXPIRES_IN,
  cache_ttl: process.env.CACHE_TTL,
  mp_access_token: process.env.MP_ACCESS_TOKEN,
  mp_public_key: process.env.MP_PUBLIC_KEY,
  mp_base_url: process.env.MP_BASE_URL,
  cookie_secret: process.env.COOKIE_SECRET,
  backend_base_url: process.env.BACKEND_BASE_URL,
  mp_payment_url: process.env.MP_PAYMENT_URL,
  email_from: process.env.EMAIL_FROM,
  email_pass: process.env.EMAIL_PASS,
  frontend_base_url: process.env.FRONTEND_BASE_URL,
  google_client_email: process.env.GOOGLE_CLIENT_EMAIL,
  google_client_private_key: process.env.GOOGLE_CLIENT_PRIVATE_KEY,
  google_sheet_id: process.env.GOOGLE_SHEET_ID,
  google_sheet_same_day_id: process.env.GOOGLE_SHEET_SAME_DAY_ID,
  cloudinary_cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  cloudinary_api_key: process.env.CLOUDINARY_API_KEY,
  cloudinary_api_secret: process.env.CLOUDINARY_API_SECRET,
  oauth_client_id: process.env.OAUTH_CLIENT_ID,
  oauth_client_secret: process.env.OAUTH_CLIENT_SECRET,
  meta_access_token: process.env.META_ACCESS_TOKEN,
  google_maps_api_key: process.env.GOOGLE_MAPS_API_KEY,
}));
